### Subject data handling

In [5]:
# Import pickle and open Subject 1 file
# using 'latin1' encoding to pickled objects
import pickle
import pandas as pd
import numpy as np

with open('../Subjects/S15/S15.pkl', 'rb') as f:
    raw_data = pickle.load(f, encoding='latin1')

In [7]:
temp_raw_data = raw_data['signal']['wrist']['TEMP']
acc_raw_data = raw_data['signal']['wrist']['ACC']
ppg_raw_data = raw_data['signal']['wrist']['BVP']
label_raw_data = raw_data['label']

In [9]:
temp_data_len = len(temp_raw_data)
acc_data_len = len(acc_raw_data)
ppg_data_len = len(ppg_raw_data)
label_data_len = len(label_raw_data)
temp_data_len, acc_data_len, ppg_data_len, label_data_len

(31756, 254048, 508096, 3966)

In [11]:
acc_raw_data.shape, acc_raw_data

((254048, 3),
 array([[-0.671875,  0.34375 ,  0.65625 ],
        [-0.703125,  0.3125  ,  0.640625],
        [-0.703125,  0.328125,  0.640625],
        ...,
        [-0.234375,  0.28125 , -0.90625 ],
        [-0.21875 ,  0.28125 , -0.90625 ],
        [-0.21875 ,  0.28125 , -0.921875]]))

In [13]:
# getting the 3 channels values to the first dimension
acc_data_converted = acc_raw_data.reshape(3*acc_data_len,1)
# converting it to a 1 dimensional array
acc_data_one_dim = acc_data_converted.flatten()
# # converting it to a non numpy array
acc_data_arr = acc_data_one_dim.tolist()
acc_data_arr[:9], len(acc_data_arr)

([-0.671875,
  0.34375,
  0.65625,
  -0.703125,
  0.3125,
  0.640625,
  -0.703125,
  0.328125,
  0.640625],
 762144)

In [572]:
# matching all data to the label array length
(temp_data_len*4)/(4*8), (acc_data_len*4)/(32*8), (ppg_data_len*4)/(64*8), label_data_len

(3969.5, 3969.5, 3969.5, 3966)

In [15]:
upd = {}
for k in raw_data["signal"]["wrist"].keys():
    upd[k] = [a[0] for a in raw_data["signal"]["wrist"][k]]

temp_one_dim = upd['TEMP']
ppg_one_dim = upd['BVP']

In [17]:
# S2 - temperature dataframe
array_of_numbers = temp_one_dim
len(array_of_numbers)

length = 32
shift = 8 # 4 Hz * 2

temp_df = pd.DataFrame()

chunks = []

for i in range(0, len(array_of_numbers), shift):
    dat = array_of_numbers[i:i + length]
    chunks.append(dat)
    temp_df = pd.concat([temp_df, pd.DataFrame([dat])], ignore_index=True)
    
temp_df.shape

(3970, 32)

In [18]:
# checking
temp_raw_data[:9], temp_df

(array([[31.09],
        [31.09],
        [31.09],
        [31.09],
        [31.07],
        [31.07],
        [31.07],
        [31.07],
        [31.07]]),
          0      1      2      3      4      5      6      7      8      9   \
 0     31.09  31.09  31.09  31.09  31.07  31.07  31.07  31.07  31.07  31.07   
 1     31.07  31.07  31.07  31.07  31.09  31.09  31.09  31.09  31.11  31.11   
 2     31.11  31.11  31.11  31.11  31.11  31.11  31.11  31.11  31.09  31.09   
 3     31.09  31.09  31.09  31.09  31.09  31.09  31.09  31.09  31.11  31.11   
 4     31.11  31.11  31.11  31.11  31.11  31.11  31.11  31.11  31.09  31.09   
 ...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
 3965  34.00  34.00  34.00  34.00  34.00  34.00  34.00  34.00  33.99  33.99   
 3966  33.99  33.99  33.99  33.99  33.99  33.99  33.99  33.99  33.99  33.99   
 3967  33.99  33.99  33.99  33.99  34.00  34.00  34.00  34.00  33.99  33.99   
 3968  33.99  33.99  33.99  33.99  33.99  33.99  33.99 

In [19]:
# S2 - accelerometer dataframe
array_of_numbers = acc_data_arr

length = 768 # 256 data points in 8 seconds * 3 channels
shift = 192 # 32 Hz * 3 channels * 2 shifts

acc_df = pd.DataFrame()

for i in range(0, len(array_of_numbers), shift):
    dat = array_of_numbers[i:i + length]
    # chunks.append(dat)
    acc_df = pd.concat([acc_df, pd.DataFrame([dat])], ignore_index=True)
    
acc_df.shape

(3970, 768)

In [28]:
# checking
acc_raw_data[:6], acc_df, len(acc_raw_data)

(array([[-0.671875,  0.34375 ,  0.65625 ],
        [-0.703125,  0.3125  ,  0.640625],
        [-0.703125,  0.328125,  0.640625],
        [-0.703125,  0.34375 ,  0.640625],
        [-0.71875 ,  0.328125,  0.609375],
        [-0.75    ,  0.34375 ,  0.609375]]),
            0         1         2         3         4         5         6    \
 0    -0.671875  0.343750  0.656250 -0.703125  0.312500  0.640625 -0.703125   
 1    -0.984375 -0.062500 -0.234375 -0.953125 -0.062500 -0.171875 -0.953125   
 2    -1.015625  0.031250 -0.109375 -1.015625  0.031250 -0.093750 -1.000000   
 3    -0.984375 -0.156250  0.203125 -0.984375 -0.140625  0.265625 -1.031250   
 4    -0.734375  0.156250  0.609375 -0.765625  0.140625  0.593750 -0.828125   
 ...        ...       ...       ...       ...       ...       ...       ...   
 3965 -0.296875 -0.015625  0.937500 -0.296875 -0.015625  0.937500 -0.296875   
 3966 -2.000000 -0.093750 -0.718750 -0.203125  0.156250 -0.234375 -1.203125   
 3967 -0.265625  0.015625  0.

In [23]:
# ppg dataframe
array_of_numbers = ppg_one_dim
len(array_of_numbers)

length = 512 # data points in 8 seconds
shift = 128 # 64 Hz * 2 shifts

ppg_df = pd.DataFrame()

for i in range(0, len(array_of_numbers), shift):
    dat = array_of_numbers[i:i + length]
    # chunks.append(dat)
    ppg_df = pd.concat([ppg_df, pd.DataFrame([dat])], ignore_index=True)
    
ppg_df.shape

(3970, 512)

In [24]:
#checking
ppg_raw_data[:9], ppg_df

(array([[-16.59],
        [-18.88],
        [-21.22],
        [-23.67],
        [-26.34],
        [-29.39],
        [-32.88],
        [-36.74],
        [-40.63]]),
         0      1      2      3      4      5      6      7      8      9    \
 0    -16.59 -18.88 -21.22 -23.67 -26.34 -29.39 -32.88 -36.74 -40.63 -43.93   
 1    -21.79 -27.48 -33.46 -40.12 -47.64 -56.21 -66.00 -76.91 -88.12 -97.94   
 2     54.97  48.97  43.21  37.76  32.54  27.37  22.07  16.55  10.87   5.22   
 3     26.58  24.97  23.46  21.78  19.62  16.76  13.17   8.92   4.12  -1.18   
 4     51.04  50.90  48.51  44.80  40.43  35.56  29.96  23.29  15.39   6.34   
 ...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
 3965  24.22  23.34  22.43  21.48  20.36  19.04  17.55  16.05  14.67  13.51   
 3966 -35.83 -38.20 -39.20 -38.33 -35.31 -30.30 -23.76 -16.46  -9.23  -2.77   
 3967   2.07   1.52   0.42  -0.96  -2.35  -3.55  -4.53  -5.45  -6.52  -7.91   
 3968  15.63  14.74  13.91  12.97  11.83  10.5

In [25]:
# label dataframe
# converting to one dimension
label_arr = label_raw_data.tolist()
#creating the dataframe
label_df = pd.DataFrame(label_arr)
label_df.shape

(3966, 1)

In [26]:
#checking
label_raw_data[:9], label_df

(array([51.78977214, 53.95587357, 59.37907894, 67.08363977, 71.92379036,
        73.97221883, 75.74545742, 77.26284956, 77.83966101]),
               0
 0     51.789772
 1     53.955874
 2     59.379079
 3     67.083640
 4     71.923790
 ...         ...
 3961  75.475622
 3962  77.524511
 3963  78.714945
 3964  80.413954
 3965  80.853007
 
 [3966 rows x 1 columns])

In [27]:
frames = [ppg_df, acc_df, temp_df, label_df]

result_df = pd.concat(frames, axis=1, ignore_index=True)
result_df

0      1      2      3      4      5      6      7      8      9     \
0    -16.59 -18.88 -21.22 -23.67 -26.34 -29.39 -32.88 -36.74 -40.63 -43.93   
1    -21.79 -27.48 -33.46 -40.12 -47.64 -56.21 -66.00 -76.91 -88.12 -97.94   
2     54.97  48.97  43.21  37.76  32.54  27.37  22.07  16.55  10.87   5.22   
3     26.58  24.97  23.46  21.78  19.62  16.76  13.17   8.92   4.12  -1.18   
4     51.04  50.90  48.51  44.80  40.43  35.56  29.96  23.29  15.39   6.34   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
3965  24.22  23.34  22.43  21.48  20.36  19.04  17.55  16.05  14.67  13.51   
3966 -35.83 -38.20 -39.20 -38.33 -35.31 -30.30 -23.76 -16.46  -9.23  -2.77   
3967   2.07   1.52   0.42  -0.96  -2.35  -3.55  -4.53  -5.45  -6.52  -7.91   
3968  15.63  14.74  13.91  12.97  11.83  10.51   9.09   7.69   6.43   5.29   
3969 -16.38  -6.12   4.35  14.16  22.63  29.37  34.09  36.71  37.27  35.99   

      ...   1303   1304   1305   1306   1307   1308   1309   1310   1311  \
0     ...  31.11  31.09  31.09  31.09  31.09  31.09  31.09  31.09  31.09   
1     ...  31.09  31.11  31.11  31.11  31.11  31.11  31.11  31.11  31.11   
2     ...  31.11  31.09  31.09  31.09  31.09  31.07  31.07  31.07  31.07   
3     ...  31.07  31.09  31.09  31.09  31.09  31.11  31.11  31.11  31.11   
4     ...  31.11  31.11  31.11  31.11  31.11  31.13  31.13  31.13  31.13   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
3965  ...  34.00  33.99  33.99  33.99  33.99  33.99  33.99  33.99  33.99   
3966  ...  33.99  33.99  33.99  33.99  33.99    NaN    NaN    NaN    NaN   
3967  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
3968  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
3969  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

           1312  
0     51.789772  
1     53.955874  
2     59.379079  
3     67.083640  
4     71.923790  
...         ...  
3965  80.853007  
3966        NaN  
3967        NaN  
3968        NaN  
3969        NaN  

[3970 rows x 1313 columns]

In [583]:
result_df.to_csv('../ppg_heart_rate_estimation/Subjects/S15/S15.csv', index=False)